//Home
export const SELECT_CITY = "SELECT_CITY";
export const SELECT_TIME = "SELECT_TIME";
export const SET_LIST_CITYS = "SET_LIST_CITYS";
export const SELECT_CITY_NAME = "SELECT_CITY_NAME";
export const CHANGE_CITY = "CHANGE_CITY";
export const FETCH_CARS = "FETCH_CARS";
export const FETCH_MOTORBIKES = "FETCH_MOTORBIKES";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const SET_NAVIGATION = "SET_NAVIGATION";
export const SELECT_TIME_CALENDAR = "SELECT_TIME_CALENDAR";
export const SELECT_DATE = "SELECT_DATE";
export const SET_NAVIGATION_HOME = "SET_NAVIGATION_HOME"
export const SET_KEY_HOME = "SET_KEY_HOME";
export const SHOW_BOOKING = "SHOW_BOOKING";
export const LOADING_HOME = "LOADING_HOME";
export const HANDLE_MODAL_TIME = "HANDLE_MODAL_TIME";

//List Vehicle

export const CHANGE_TAB = "CHANGE_TAB";
export const CHANGE_LIST_CARS = "CHANGE_LIST_CARS";
export const CHANGE_LIST_MOTORBIKES = "CHANGE_LIST_MOTORBIKES";
export const INIT_MODAL = "INIT_MODAL";
export const SORT_VEHICLE = "SORT_VEHICLE";
export const SELECT_DELIVERY_ADDRESS = "SELECT_DELIVERY_ADDRESS";
export const SELECT_VEHICLE = "SELECT_VEHICLE";
export const LOAD_DETAIL = "LOAD_DETAIL";
export const LOADING_LIST = "LOADING_LIST";
export const FINiSH_LOAD_MOTORBIKE ="FINiSH_LOAD_MOTORBIKE";
export const FINiSH_LOAD_CAR = "FINiSH_LOAD_CAR";
export const SCROLL_FILTER = "SCROLL_FILTER";
export const OPEN_FILTER ="OPEN_FILTER";
export const CHANGE_FILTER_CAR = "CHANGE_FILTER_CAR"

//DetailVehicle

export const CHANGE_DELIVERY = "CHANGE_DELIVERY";
export const INIT_PRICE = "INIT_PRICE";
export const CHANGE_PROMOTION = "CHANGE_PROMOTION";
export const LOAD_PROMO = "LOAD_PROMO";
export const CACULATE_DAY_NUM = "CACULATE_DAY_NUM";

//CustomerInfo

export const CHANGE_FULLNAME = "CHANGE_FULLNAME";
export const CHANGE_PHONE = "CHANGE_PHONE";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_NOTE = "CHANG_NOTE";
export const SET_BOOKING = "SET_BOOKING";
export const INIT_CUSTOMER_INFO = "INIT_CUSTOMER_INFO";
export const HANDLE_FOCUS = "HANDLE_FOCUS";

//User
export const CHANGE_USERNAME_LOGIN = "CHANGE_USERNAME_LOGIN";
export const CHANGE_PASSWORD_LOGIN = "CHANGE_PASSWORD_LOGIN";
